services:
  mysql:
    image: mysql:8.0
    container_name: outbox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: outbox_pattern_poc
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  firebase-emulator:
    build:
      context: .
      dockerfile: docker/firebase-emulator/Dockerfile
    container_name: outbox-firebase-emulator
    volumes:
      - ./firebase.json:/app/firebase.json
    ports:
      - "18085:8085"
      - "18080:8080"
      - "14000:4000"
      - "14400:4400"
    command: /bin/sh -c "firebase emulators:start"
    restart: always
    working_dir: /app

volumes:
  mysql-data:
